# Use root/example as user/password credentials
version: "3"

services:
    server:
        container_name: NODEJS_SERVER
        build: "."
        volumes:
            - ./:/node-app
            - ./node_modules:/node-app/node_modules
        environment:
            NODE_ENV: development
        depends_on:
            - mongo
        links:
            - mongo
        ports:
            - "8000:8000"

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
